### ISSUE TITLE
Texpad 打开文件时编码错误

### ISSUE THREAD

**Issue by jxxiao** [CTeX-org/chinesejournal#1]
## 编译环境
- 编译的系统：macOS 10.14
- TeX 发行版：MacTeX 2019
- 相关宏包版本：ctex v2.4.14 | unicode-math v0.8l

## 描述问题
texpad打开直接乱码

截图：
![image](https://user-images.githubusercontent.com/15158054/58092848-b54b5200-7bff-11e9-872f-edd0332c6665.png)

**Comment by zepinglee** [comment]
需要用 UTF-8 编码

**Comment by zepinglee** [comment]
另外这个项目处于初步开发阶段，欢迎提出建议！

**Comment by jxxiao** [comment]
编码错误的问题我解决了，但是排版时还是有问题，和上图右边是一样的。

**Comment by zepinglee** [comment]
用 xelatex 编译

**Comment by jxxiao** [comment]
谢谢，因为我现在想修改这个模版，但我执行make的时候，会提示“bash: latexmk: command not found”，我是安装了完整mactex的.

**Comment by zepinglee** [comment]
这说明 latexmk 所在的目录没有加到 PATH 里。

你可以试一下手动加到 PATH 再编译：
```
export PATH="/usr/local/texlive/2019/bin/x86_64-darwin:$PATH"
```

另外问下你是编辑还是 LaTeX 爱好者？

**Comment by jxxiao** [comment]
学生，最近写作业准备用latex写，所以在折腾这个东西。以前只是在markdown里插过latex公式，对编译这些不太了解。

**Comment by zepinglee** [comment]
嗯，那我不太建议使用这个模板，因为这个项目的初衷是为期刊出版社编辑提供一个高质量的模板范例，目前完成度可能还不到 10%。所以建议使用其他较为成熟的模板。

**Comment by jxxiao** [comment]
我们的作业的word模版就是这个，只是在页眉处没有计算机学报等信息。所以，我才想到用这个模版。

**Comment by zepinglee** [comment]
目前这个模板《[计算机学报](http://cjc.ict.ac.cn)》跟官方要求的格式还不完全一致。

鉴于你似乎还没有太多写模板的经验，你不妨帮忙列举出模板中需要调整格式的位置（aka 挑刺），然后由我来修改模板。

**Comment by jxxiao** [comment]
摘要的格式和计算机学报的要求目前还不一样的。

**Comment by Luzeru** [comment]
> 编码错误的问题我解决了，但是排版时还是有问题，和上图右边是一样的。

你好，请问你是怎么解决这个中文乱码的问题，我的也出现的了这个问题，texpad编辑出来的pdf也都是乱码。
而且我的原文没有备份，现在我恢复不出来原始的中文内容了。
请赐教。
