### ISSUE TITLE
编译后的文档不显示作者信息，摘要和正文之间没有空行。

### ISSUE THREAD

**Issue by Aierhaimian** [CTeX-org/chinesejournal#2]
## 编译环境
- 编译的系统：macOS 10.14.15
- TeX 发行版：MacTeX 2019
- 相关宏包版本：ctex v2.4.14 | unicode-math v0.8l

## 描述问题

我clone了作者的仓库后，按照README.md中的介绍，首先进行了make doc操作，编译完成后继续进行了make操作，此时生成了main.pdf文档，但是此文档中没有作者的相关信息显示，而且英文摘要和正文之间没有空行。

截图：
![image](https://user-images.githubusercontent.com/29089426/59999827-7c3a4d80-9695-11e9-88d1-d0d92477dd76.png)
![image](https://user-images.githubusercontent.com/29089426/59999854-8e1bf080-9695-11e9-8faa-f74833bcd1d4.png)

**Comment by zepinglee** [comment]
感谢关注！

1. 作者的信息比较复杂，我还没设计好接口。

2. 英文摘要和正文之间的空白还需要调整。

**Comment by yhZhai** [comment]
作者你好，我也遇到了同样的问题，请问有没有解决方案？或者在其他操作系统（Winodows, Linux）下有没有同样的问题？
谢谢！

**Comment by zepinglee** [comment]
> 作者你好，我也遇到了同样的问题，请问有没有解决方案？或者在其他操作系统（Winodows, Linux）下有没有同样的问题？
> 谢谢！

最近懒，没怎么搞这个项目

**Comment by yihuiliang** [comment]
> ## 编译环境
> * 编译的系统：macOS 10.14.15
> * TeX 发行版：MacTeX 2019
> * 相关宏包版本：ctex v2.4.14 | unicode-math v0.8l
> 
> ## 描述问题
> 我clone了作者的仓库后，按照README.md中的介绍，首先进行了make doc操作，编译完成后继续进行了make操作，此时生成了main.pdf文档，但是此文档中没有作者的相关信息显示，而且英文摘要和正文之间没有空行。
> 
> 截图：
> ![image](https://user-images.githubusercontent.com/29089426/59999827-7c3a4d80-9695-11e9-88d1-d0d92477dd76.png)
> ![image](https://user-images.githubusercontent.com/29089426/59999854-8e1bf080-9695-11e9-8faa-f74833bcd1d4.png)

同问，期待作者更新

**Comment by ozzie00** [comment]
期待作者更新

**Comment by Mrhs121** [comment]
我这里用了一个简答粗暴的办法显示作者
[参考我fork的版本](https://github.com/Mrhs121/chinesejournal)
<img width="844" alt="截屏2020-02-14 上午10 47 22" src="https://user-images.githubusercontent.com/15990723/74497509-d59f0780-4f18-11ea-9bce-cefa77b3fed7.png">

**Comment by stargazer1sdh** [comment]
同问题。期待作者更新

**Comment by zepinglee** [comment]
在 304935f 中修复。

**Comment by Liam0205** [comment]
@zepinglee 你可以在 commit log 里写上：「fix #2」。这样当相应 commit 被 push/merge 到 master 之后，相应的 issue 会被自动关闭。
