### ISSUE TITLE
计算机学报的格式问题

### ISSUE THREAD

**Issue by xpyqiubai** [CTeX-org/chinesejournal#5]
## 编译环境
- 编译的系统：Windows 17
- TeX 发行版：TeX Live 2019 
- 相关宏包版本：ctex v2.4.14 | unicode-math v0.8l

## 描述问题

您好，感谢您分享计算机学报的模板，但是在首页的收稿日期页脚那里应该是单栏的而不是双栏的，可否向您请教该如何调整，谢谢

**Comment by zepinglee** [comment]
这个在 LaTeX 的机制下几乎无法实现。

你可以去看其他的 LaTeX 双栏模板，比如 revtex, ICML, CVPR 的模板，脚注都是在其中一栏的范围内。

**Comment by xpyqiubai** [comment]
> 这个在 LaTeX 的机制下几乎无法实现。
> 
> 你可以去看其他的 LaTeX 双栏模板，比如 revtex, ICML, CVPR 的模板，脚注都是在其中一栏的范围内。

感谢您，我查了好多发现确实没找到有解决的

**Comment by zepinglee** [comment]
> 感谢您，我查了好多发现确实没找到有解决的

我也尝试过 hack LaTeX 底层代码，但是并不好解决。

**Comment by xpyqiubai** [comment]
> 这个在 LaTeX 的机制下几乎无法实现。
> 
> 你可以去看其他的 LaTeX 双栏模板，比如 revtex, ICML, CVPR 的模板，脚注都是在其中一栏的范围内。

最无奈的是计算机学报给了个下载latex模板的链接，但是根本没有模板，感觉好多中文核心都没有latex版本，稍微有点无奈

**Comment by zepinglee** [comment]
目前大部分中文期刊 LaTeX 模板的质量……真不如不用

**Comment by Kitaharakasusa** [comment]
> > 这个在 LaTeX 的机制下几乎无法实现。
> > 你可以去看其他的 LaTeX 双栏模板，比如 revtex, ICML, CVPR 的模板，脚注都是在其中一栏的范围内。
> 
> 最无奈的是计算机学报给了个下载latex模板的链接，但是根本没有模板，感觉好多中文核心都没有latex版本，稍微有点无奈

请问您之后是怎么解决的呢，我也遇到了这个问题，还有第一作者照片插入的问题。

**Comment by xpyqiubai** [comment]
最终还是用word写的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CTeX-org/chinesejournal"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月13日(星期五) 晚上7:01
收件人:&nbsp;"CTeX-org/chinesejournal"<chinesejournal@noreply.github.com&gt;;
抄送:&nbsp;"549792035"<549792035@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CTeX-org/chinesejournal] 计算机学报的格式问题 (#5)





   
这个在 LaTeX 的机制下几乎无法实现。
 你可以去看其他的 LaTeX 双栏模板，比如 revtex, ICML, CVPR 的模板，脚注都是在其中一栏的范围内。
  
最无奈的是计算机学报给了个下载latex模板的链接，但是根本没有模板，感觉好多中文核心都没有latex版本，稍微有点无奈
  
请问您之后是怎么解决的呢，我也遇到了这个问题，还有第一作者照片插入的问题。
